{% set name = "jupyter-ai" %}
{% set version = "2.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai-{{ version }}.tar.gz
  sha256: 36230a9530a9c4b97bbf89b701e378c027686811c12e24849aa43925d4716848

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyter_server >=1.6,<3
    - jupyterlab >=4.0,<5
    - aiosqlite >=0.18
    - importlib-metadata >=5.2.0
    - jupyter-ai-magics ==2.25.0
    - dask-core
    - typing-extensions >=4.5.0
    - distributed
    - traitlets >=5.0,<6
    - deepmerge >=2.0,<3
    # faiss-cpu>=1.8.0 is installed via `./post-link.sh`

test:
  requires:
    - pip
  imports:
    - jupyter_ai
  commands:
    - pip check

about:
  summary: A generative AI extension for JupyterLab
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JasonWeill
    - dlqqq
    - 3coins
    - andrii-i
