{% set name = "jupyter-ai" %}
{% set version = "2.31.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai-{{ version }}.tar.gz
  sha256: 4ff280604c784ded3de5efa45f39965f8eaf0386a2a581c05977265c47d395b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.4,<3
    - importlib-metadata >=5.2.0
    - pydantic >=2.10.0,<3
    - jupyter-ai-magics >=2.31.5,<3
    - dask-core
    - distributed
    - faiss-cpu >=1.8.0,<2
    - traitlets >=5.6,<6
    - deepmerge >=2.0,<3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_ai

about:
  summary: A generative AI extension for JupyterLab
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - andrii-i
    - srdas
