{% set name = "jupyter-ai" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai-{{ version }}.tar.gz
  sha256: 8c423164e87a0c0a7ecba638cb3240577590af65c3e16df1ac2dae2703997df4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - langchain-community <0.0.8
    - langchain-core >=0.1.0,<0.1.4
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyter_server >=1.6,<3
    - jupyterlab >=4.0,<5
    - openai >=0.26,<1
    - aiosqlite >=0.18
    - importlib-metadata >=5.2.0
    - langchain ==0.0.350
    - tiktoken
    - jupyter-ai-magics ==2.8.1
    - dask-core
    - typing-extensions >=4.5.0
    - distributed
    - faiss-cpu
    - traitlets >=5.0,<6
    - deepmerge >=1.0,<2

test:
  requires:
    - pip
  imports:
    - jupyter_ai
  commands:
    - pip install faiss-cpu
    - pip check

about:
  summary: A generative AI extension for JupyterLab
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JasonWeill
    - dlqqq
    - 3coins
    - andrii-i
