{% set name = "jupyter-ai" %}
{% set version = "2.28.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai-{{ version }}.tar.gz
  sha256: 0749215341be2d470c85c39605d8b3132f24f444355b067532b511c35d210bff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - jupyter_server >=1.6,<3
    - jupyterlab >=4.0,<5
    - aiosqlite >=0.18
    - importlib-metadata >=5.2.0
    - jupyter-ai-magics ==2.28.5
    - dask-core
    - typing-extensions >=4.5.0
    - distributed
    - traitlets >=5.0,<6
    - deepmerge >=2.0,<3
    - faiss-cpu >=1.8.0,<2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_ai

about:
  summary: A generative AI extension for JupyterLab
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - andrii-i
    - srdas
