context:
  version: "3.0.0rc0"

package:
  name: jupyter-ai
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai/jupyter_ai-${{ version }}.tar.gz
  sha256: c3b959f2cd09d9365d6d176b7f2d79d40bc8480ee7051ac5b0bfc9ee97e86f16

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >=${{ python_min }}
    - jupyter-ai-acp-client >=0.0.8
    - jupyter-ai-chat-commands >=0.0.4
    - jupyter-ai-persona-manager >=0.0.8
    - jupyter-ai-router >=0.0.3
    - jupyter-ai-tools >=0.4.1
    - jupyter_server_documents >=0.1.1
    - jupyter-server-mcp >=0.1.2
    - jupyterlab-chat >=0.20.0
    - jupyterlab-notebook-awareness

tests:
  - python:
      imports:
        - jupyter_ai
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/jupyterlab/jupyter-ai
  repository: https://github.com/jupyterlab/jupyter-ai
  documentation: https://jupyter-ai.readthedocs.io/en/v3/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A set of extensions providing agentic AI in JupyterLab"

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - andrii-i
    - srdas
